// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ApiClient.Models
{
    using Newtonsoft.Json;

    public partial class STUDENT
    {
        /// <summary>
        /// Initializes a new instance of the STUDENT class.
        /// </summary>
        public STUDENT() { }

        /// <summary>
        /// Initializes a new instance of the STUDENT class.
        /// </summary>
        public STUDENT(int? id = default(int?), string fIRSTNAME = default(string), string lASTNAME = default(string), string pHONENO = default(string))
        {
            ID = id;
            FIRSTNAME = fIRSTNAME;
            LASTNAME = lASTNAME;
            PHONENO = pHONENO;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ID")]
        public int? ID { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "FIRST_NAME")]
        public string FIRSTNAME { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "LAST_NAME")]
        public string LASTNAME { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PHONE_NO")]
        public string PHONENO { get; set; }

    }
}
